### ISSUE TITLE
Setting wallpaper in background automatically (question)

### ISSUE THREAD

**Issue by jasan-s** [sahilverma-dev/react-native-wallpaper-util#1]
Is it possible to change the wallpaper automatically in the background using this lib?

I wanted to set a dynamic wallpaper based on time automatically. Or does it require user interaction to change it while the app is in foreground?

**Comment by sahilverma-dev** [comment]
This utility function provides a simple way to set wallpapers on your React Native application. It is an enhanced version based on the work of [Ajay Bhatia](https://github.com/ajaybhatia), who originally created the [react-native-wallpaper-manager](https://github.com/ajaybhatia/react-native-wallpaper-manager) library. The original repository is currently not maintained and lacks TypeScript support.

And I don't know much about native modules and not sure if this package actually works or not.
